### ISSUE TITLE
Can you share your casia nir vis 2.0 dataset with me, thanks a lot

### ISSUE THREAD

**Issue by KawhiZhao** [shashankvkt/dualranking_TIFS_2018#1]

**Comment by shashankvkt** [comment]
Sorry for the late reply. Unfortunately, I do not own the rights to share or distribute the dataset. However you can place a request to the dataset owners using the following link https://www.beat-eu.org/platform/databases/cbsr_nir_vis_2/2/
In case you are not able to find it, kindly email the authors and I am sure they will respond.
